#!/usr/bin/env php
<?php
require_once('vendor' . DIRECTORY_SEPARATOR . 'autoload.php');

use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new \Pixplorer\Command\Test\Interaction1Command());
$application->add(new \Pixplorer\Command\Test\Audio1Command());
$application->run();
